language: python

python:
  - 3.5

install:
    - sudo apt-get install libjpeg-dev libfreetype6 libfreetype6-dev zlib1g-dev
    - sudo ln -s /lib/x86_64-linux-gnu/libz.so.1 /lib/
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so.6 /usr/lib/
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so.62 /usr/lib/

    - pip3 install encrypter_pictures

script:
    - python3.4 -c"from PIL import Image"
